modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="karel_mod"
version="1.0.0"
displayName="Karel Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="royal, MCreator"

[[dependencies.karel_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




